name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-cli:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build CLI Executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile caption_openai.py

      - name: Create CLI Package
        run: |
          mkdir vlm-caption-cli
          copy dist\caption_openai.exe vlm-caption-cli\
          copy caption.yaml vlm-caption-cli\
          copy character_info.txt vlm-caption-cli\
          copy *.MD vlm-caption-cli\
          powershell Compress-Archive -Path vlm-caption-cli\* -DestinationPath vlm-caption-cli.zip

      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vlm-caption-cli
          path: vlm-caption-cli.zip

  build-electron:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: |
          cd ui
          npm install

      - name: Build Electron App
        run: |
          cd ui
          npm run build:electron

      - name: Upload Electron Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vlm-caption-electron
          path: ui/dist/*.exe

  create-release:
    needs: [build-cli, build-electron]
    runs-on: windows-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download CLI Artifact
        uses: actions/download-artifact@v4
        with:
          name: vlm-caption-cli

      - name: Download Electron Artifact
        uses: actions/download-artifact@v4
        with:
          name: vlm-caption-electron

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: VLM Caption v${{ github.run_number }}
          body: |
            Automated release containing both CLI and GUI versions of VLM Caption.
            
            📦 **Downloads:**
            - `vlm-caption-cli.zip` - Command-line version
            - `VLM Caption Setup *.exe` - GUI version (Windows installer)
            
            🚀 **What's New:**
            - Latest updates from commit ${{ github.sha }}
          files: |
            vlm-caption-cli.zip
            *.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
